/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        neon: {
          blue: '#00f3ff',
          purple: '#b026ff',
          pink: '#ff007f',
          green: '#00ff66'
        },
        dark: {
          900: '#050505',
          800: '#0a0a0c',
          700: '#111116',
          600: '#1a1a24'
        },
        "on-secondary-container": "#fffbff",
        "tertiary-fixed": "#e9ddff",
        "tertiary-container": "#360084",
        "primary-fixed-dim": "#b6c6ef",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-container-low": "#eff4ff",
        "inverse-surface": "#213145",
        "error-container": "#ffdad6",
        "surface-variant": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1a2b4b",
        "on-tertiary-fixed": "#23005c",
        "on-secondary-fixed": "#0f0069",
        "secondary": "#4b41e1",
        "primary-fixed": "#d8e2ff",
        "on-secondary-fixed-variant": "#3323cc",
        "on-background": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#e2dfff",
        "primary": "#031635",
        "on-tertiary-container": "#a27bff",
        "secondary-fixed-dim": "#c3c0ff",
        "secondary-container": "#645efb",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface-variant": "#44474e",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#364768",
        "inverse-on-surface": "#eaf1ff",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "outline": "#75777f",
        "inverse-primary": "#b6c6ef",
        "surface-tint": "#4e5e81",
        "surface-dim": "#cbdbf5",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "outline-variant": "#c5c6cf",
        "on-primary-container": "#8293b8",
        "surface-container": "#e5eeff",
        "on-primary-fixed": "#081b3a",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed-dim": "#d0bcff",
        "tertiary": "#1e0050"
      },
      fontFamily: {
        orbitron: ['Orbitron', 'sans-serif'],
        rajdhani: ['Rajdhani', 'sans-serif'],
        exo: ['Exo 2', 'sans-serif'],
        "data-mono": ["Geist", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "monospace"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "data-mono": ["14px", {"lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      },
      spacing: {
        "container-max": "1440px",
        "xs": "4px",
        "md": "16px",
        "gutter": "20px",
        "xl": "40px",
        "lg": "24px",
        "base": "4px",
        "sm": "8px"
      },
      boxShadow: {
        'neon-blue': '0 0 10px #00f3ff, 0 0 20px #00f3ff',
        'neon-purple': '0 0 10px #b026ff, 0 0 20px #b026ff',
      },
      backgroundImage: {
        'glass-gradient': 'linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.01) 100%)',
      }
    },
  },
  plugins: [],
}
