"""Add email verification token

Revision ID: 2d5d36ba7a82
Revises: a0a728bd78c8
Create Date: 2026-06-10 15:48:48.245245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5d36ba7a82'
down_revision: Union[str, None] = 'a0a728bd78c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('gst_transactions', sa.Column('is_taxable', sa.Boolean(), nullable=True))
    op.add_column('gst_transactions', sa.Column('is_statutory', sa.Boolean(), nullable=True))
    op.add_column('gst_transactions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('gst_transactions', 'hsn_sac_code')
    op.drop_column('gst_transactions', 'total_tax')
    op.drop_column('gst_transactions', 'return_period')
    op.drop_column('gst_transactions', 'reverse_charge')
    op.drop_column('gst_transactions', 'itc_eligible')
    op.drop_column('gst_transactions', 'place_of_supply')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gst_transactions', sa.Column('place_of_supply', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('gst_transactions', sa.Column('itc_eligible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('gst_transactions', sa.Column('reverse_charge', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('gst_transactions', sa.Column('return_period', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('gst_transactions', sa.Column('total_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('gst_transactions', sa.Column('hsn_sac_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('gst_transactions', 'is_active')
    op.drop_column('gst_transactions', 'is_statutory')
    op.drop_column('gst_transactions', 'is_taxable')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
